version: '3'
services:
  jekyll:
    build: .
#    environment:
#      - "JEKYLL_GITHUB_TOKEN:${JEKYLL_GITHUB_TOKEN}"
    ports:
      - "4000:4000"
    volumes:
      - ./:/usr/src/app
    tty: true
    entrypoint: bundle exec jekyll serve --watch --force_polling -H 0.0.0.0 -P 4000
